### ISSUE TITLE
'layer demo' doesn't work in x16emu r34

### ISSUE THREAD

**Issue by mobluse** [commanderx16/x16-demo#82]
'layer demo' doesn't work in x16emu r34. It worked in x16emu r33, but doesn't work in r34 or the latest from master on GitHub. This is probably due to changed addresses in RAM. One could find these addresses in rom.sym from r33 and then look up what they should be in rom.sym for r34.

**Comment by Techrev9999** [comment]
It's definitely causing a problem when it writes to $FC.  Zero page changed, and now that pretty much causes a hard crash.  I changed it to $7C, and it doesn't hard crash, but I don't think it's doing what it's supposed to do.  I think there's supposed to be characters displayed in the back layer, and it's black.  Still, forward progress.

**Comment by Techrev9999** [comment]
It doesn't seem to be an issue that can be found in the roms.sym files. I did windiffs on those, and nothing in there affected this. That one big issue I found had to do with zero page remapping. The other seems to be, from what I can tell, a change in how the layers are set up and defined.

**Comment by jestin** [comment]
The layer demo should be fixed for r34, r35, and r36.  I created a PR that has recently been merged.

Unfortunately, it is broken again in r37 and and r38, due to exposing VERA addresses through the memory map in VERA 0.9.  I have created a [pull request](https://github.com/commanderx16/x16-demo/pull/106) to fix this, although it has the caveat that the electricity animation is broken.

I would recommend that this issue be closed, since the original problems have been addressed.
